from domains import *

INTERKIDSY_CATEGORY = INTERKIDSY_DOMAIN + 'ru/'
ZEYDANKIDS_CATEGORY = ZEYDANKIDS_DOMAIN + 'urunler/kategori/'

# GIRLS
GIRL_DRESS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'platye-dlya-devochki',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '357',
}

GIRL_TOP = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'topy-dlya-devochek',
    ZEYDANKIDS_DOMAIN: None,
}

GIRL_SHOES = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'obuv-dlya-devochek',
    ZEYDANKIDS_DOMAIN: None,
}

GIRL_SET = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'komplekty-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '359',
}

GIRL_TROUSERS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'bryuki-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '414',
}

GIRL_UNDERWEAR = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'nizhneye-belye-i-noski-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '430',
}

GIRL_OVERALLS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'kombinezony-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '432',
}

GIRL_PAJAMAS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'pizhamy-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '386',
}

GIRL_SHIRT = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'rubashki-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '397',
}

GIRL_OUTERWEAR = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'verkhnyaya-odezhd-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '309',
}

# BOYS
BOY_SET = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'komplekty-dlya-mal-chikov',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '369',
}

BOY_TROUSERS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'bryuki-dlya-malchikov',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '362',
}

BOY_UNDERWEAR_PAJAMAS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'pizhamy-nizhneye-belye-noski',
    ZEYDANKIDS_DOMAIN: (
        ZEYDANKIDS_CATEGORY + '429',
        ZEYDANKIDS_CATEGORY + '385',
    ),
}

BOY_TOP = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'topy-dlya-malchikov',
    ZEYDANKIDS_DOMAIN: None,

}

BOY_SHOES = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'obuv-dlya-malchikov',
    ZEYDANKIDS_DOMAIN: None,
}

BOY_PAJAMAS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'pizhamy-dlya-malchikov',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '385',
}

BOY_SHIRT = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'rubashka-dlya-malchika',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '402',
}

BOY_COSTUME = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'kostyum-dlya-malchika',
    ZEYDANKIDS_DOMAIN: None,
}

BOY_OUTERWEAR = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'verkhnyaya-odezhda-dlya-malchikov',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '425',
}
