INTERKIDSY_DOMAIN = 'www.interkidsy.com/'
ZEYDANKIDS_DOMAIN = 'www.zeydankids.com/'

INTERKIDSY_CATEGORY = INTERKIDSY_DOMAIN + 'ru/'
ZEYDANKIDS_CATEGORY = ZEYDANKIDS_DOMAIN + 'urunler/kategori/'

# GIRLS
GIRL_DRESS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'platye-dlya-devochki',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '357',
}

GIRL_TOP = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'topy-dlya-devochek',
    ZEYDANKIDS_DOMAIN: None,
}

GIRL_SHOES = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'obuv-dlya-devochek',
    ZEYDANKIDS_DOMAIN: None,
}

GIRL_SET = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'komplekty-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '359',
}

GIRL_TROUSERS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'bryuki-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '414',
}

GIRL_UNDERWEAR = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'nizhneye-belye-i-noski-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '430',
}

GIRL_OVERALLS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'kombinezony-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '432',
}

GIRL_PAJAMAS = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'pizhamy-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '386',
}

GIRL_SHIRT = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'rubashki-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '397',
}

GIRL_OUTERWEAR = {
    INTERKIDSY_DOMAIN: INTERKIDSY_CATEGORY + 'verkhnyaya-odezhd-dlya-devochek',
    ZEYDANKIDS_DOMAIN: ZEYDANKIDS_CATEGORY + '309',
}

# BOYS
