version: "3"

services:
  backend:
    build:
      context: server/
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "7000:7000"
