line-length = 120

[lint]
select = [
    "ERA", # no commented-out code
    "T201", # no prints
    'C90', # mccabe
    'N', # pep8-naming
    'S', # bandit
    'BLE', # flake8-blind-except
    'B', # bugbear
    'C4', # comprehensions
    'DTZ', # datetimez
    'EM', # error-messages
    'PIE', # flake8-pie
    'PT', # flake8-pytest-style
    'SLF', # flake8-self
    'S' # flake8-string-format
]

[format]
quote-style = 'single'
