exclude = [
    '__init__.py'
]
line-length = 120

[lint]
select = [
    'C90', # mccabe
    'N', # pep8-naming
    'S', # bandit
    'BLE', # flake8-blind-except
    'B', # bugbear
    'C4', # comprehensions
    'DTZ', # datetimez
    'EM', # error-messages
    'FA', # future-annotations
    'PIE', # flake8-pie
    'PT', # flake8-pytest-style
    'SLF', # flake8-self
    'S' # flake8-string-format
]

[format]
quote-style = 'single'
